name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: some-deployment-action
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }} 
