name: Static Code Analysis
on:
  pull_request:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run static code analysis
        run: npm run lint

        